PRINT '[dbo].[tblBook] SCHEMA'

IF OBJECT_ID('[dbo].[tblBook]') IS NULL
BEGIN
	CREATE TABLE [dbo].[tblBook](
		[BookID] [int] IDENTITY(1,1) NOT NULL,
		[Name] [varchar](50) NOT NULL,
	 CONSTRAINT [PK_tblBook] PRIMARY KEY CLUSTERED 
	(
		[BookID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

GO